# Generated by Django 5.2.7 on 2025-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="high_protein",
            field=models.BooleanField(default=False, verbose_name="Высокобелковое"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="no_sugar",
            field=models.BooleanField(
                default=False, verbose_name="Без добавленного сахара"
            ),
        ),
    ]
