# Generated by Django 4.2.25 on 2025-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_meal_type_userprofile_breakfast_blocked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.CharField(blank=True, help_text='Через запятую: арахис, молоко, яйца', max_length=200, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция приготовления'),
        ),
    ]
