# Generated by Django 5.2.7 on 2025-10-27 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Завтрак"),
                    ("lunch", "Обед"),
                    ("dinner", "Ужин"),
                ],
                default="lunch",
                max_length=20,
                verbose_name="Тип приема пищи",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="breakfast_blocked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Блокировка завтрака до"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="breakfast_refresh_count",
            field=models.IntegerField(
                default=0, verbose_name="Счетчик обновлений завтрака"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dinner_blocked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Блокировка ужина до"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dinner_refresh_count",
            field=models.IntegerField(
                default=0, verbose_name="Счетчик обновлений ужина"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disliked_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_by",
                to="recipes.recipe",
                verbose_name="Дизлайкнутые рецепты",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="filters",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Фильтры пользователя"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_refresh_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата последнего обновления",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lunch_blocked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Блокировка обеда до"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lunch_refresh_count",
            field=models.IntegerField(
                default=0, verbose_name="Счетчик обновлений обеда"
            ),
        ),
    ]
